### ISSUE TITLE
Does handoutWithNotes work with Overleaf?

### ISSUE THREAD

**Issue by noamsgl** [gdiepen/latexbeamer-handoutWithNotes#12]
Hey, looks like a great module for my needs!

Is there a minimal working example for using this with OverLeaf?
I am getting this error 

![image](https://user-images.githubusercontent.com/44804339/168430671-6bcf54f9-1a3b-4dcc-8bf3-29d0782c64bf.png)

Even though all the files are right next to my `main.tex`

![image](https://user-images.githubusercontent.com/44804339/168430699-17379da9-77e8-4f63-a2a2-8ce33c7dc420.png)

Thanks!

**Comment by TeXhackse** [comment]
Yes it works with Overleaf. But Overleaf is only updating the distribution rarely because they do some adjustments.

The contents of this repo is a source including the documentation. The system used for this is l3build. You can have a look at the corresponding texdoc for more information about it. I will do some testing if it's possible to compile it using Overleaf itself, but I am not sure if it is because Overleaf mostly builds pdf files.

Anyway I dropped the sty file in the latest release Version here: (link removed because github internal link can be found below)

Then it should be able to be used in Overleaf. Since this issue will be resolved with overleaf Updating the TeX Live it will disappear automatically. We just prepared the first CTAN after Overleafs last Update and they are not yet on TL2022 which will include it from the first release.

**Comment by TeXhackse** [comment]
I did now also attach the *.sty file to the release: https://github.com/gdiepen/latexbeamer-handoutWithNotes/releases/download/v1.3/handoutWithNotes.sty
